//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package builtins

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
