package structs

import (
	"time"

	"github.com/ravinggo/objectpool"
)

// +k8s:deepcopy-gen=false
type DateFields struct {
	CreateAt time.Time `json:"create_at" bson:"create_at"`
	UpdateAt time.Time `json:"update_at" bson:"update_at"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (this_ *DateFields) DeepCopyInto(ka *objectpool.KeepAlive, out *DateFields) {
	*out = *this_
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateFields.
func (this_ *DateFields) DeepCopy(ka *objectpool.KeepAlive) *DateFields {
	if this_ == nil {
		return nil
	}
	out := new(DateFields)
	this_.DeepCopyInto(ka, out)
	return out
}
