//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package structs

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Inner) DeepCopyInto(ka *objectpool.KeepAlive, out *Inner) {
	*out = *in
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Inner.
func (in *Inner) DeepCopy(ka *objectpool.KeepAlive) *Inner {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Inner](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Inner1 != nil {
		in, out := &in.Inner1, &out.Inner1
		*out = objectpool.GetKA[Inner](ka)
		(*in).DeepCopyInto(ka, *out)
	}
	in.Inner2.DeepCopyInto(ka, &out.Inner2)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
