//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ___go_build_github_com_ravinggo_game_common_tools_deepcopy_gen. DO NOT EDIT.

package structs

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Inner) DeepCopyInto(ka *objectpool.KeepAlive, out *Inner) {
	*out = *in
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Inner.
func (in *Inner) DeepCopy(ka *objectpool.KeepAlive) *Inner {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Inner](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Inner1 != nil {
		in, out := &in.Inner1, &out.Inner1
		*out = objectpool.GetKA[Inner](ka)
		(*in).DeepCopyInto(ka, *out)
	}
	in.Inner2.DeepCopyInto(ka, &out.Inner2)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Unlock) DeepCopyInto(ka *objectpool.KeepAlive, out *Unlock) {
	*out = *in
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = objectpool.GetKAMap[int32, map[int64]int64](ka)
		for key, val := range *in {
			var outVal map[int64]int64
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKAMap[int64, int64](ka)
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Unlocked != nil {
		in, out := &in.Unlocked, &out.Unlocked
		*out = objectpool.GetKAMap[int32, map[int64]bool](ka)
		for key, val := range *in {
			var outVal map[int64]bool
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKAMap[int64, bool](ka)
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	in.DateFields.DeepCopyInto(ka, &out.DateFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Unlock.
func (in *Unlock) DeepCopy(ka *objectpool.KeepAlive) *Unlock {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Unlock](ka)
	in.DeepCopyInto(ka, out)
	return out
}
