//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package pointer

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = objectpool.GetKA[string](ka)
		**out = **in
	}
	if in.Ptr != nil {
		in, out := &in.Ptr, &out.Ptr
		*out = objectpool.GetKA[*string](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKA[string](ka)
			**out = **in
		}
	}
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = objectpool.GetKA[map[string]string](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKAMap[string, string](ka)
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.Slice != nil {
		in, out := &in.Slice, &out.Slice
		*out = objectpool.GetKA[[]string](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
			copy(*out, *in)
		}
	}
	if in.MapPtr != nil {
		in, out := &in.MapPtr, &out.MapPtr
		*out = objectpool.GetKA[*map[string]string](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKA[map[string]string](ka)
			if **in != nil {
				in, out := *in, *out
				*out = objectpool.GetKAMap[string, string](ka)
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.SlicePtr != nil {
		in, out := &in.SlicePtr, &out.SlicePtr
		*out = objectpool.GetKA[*[]string](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKA[[]string](ka)
			if **in != nil {
				in, out := *in, *out
				*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
		}
	}
	if in.Struct != nil {
		in, out := &in.Struct, &out.Struct
		*out = objectpool.GetKA[Ttest](ka)
		(*in).DeepCopyInto(ka, *out)
	}
	if in.StructPtr != nil {
		in, out := &in.StructPtr, &out.StructPtr
		*out = objectpool.GetKA[*Ttest](ka)
		if **in != nil {
			in, out := *in, *out
			*out = objectpool.GetKA[Ttest](ka)
			(*in).DeepCopyInto(ka, *out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
