//go:build !ignore_autogenerated_zerolog
// +build !ignore_autogenerated_zerolog

// Code generated by zerolog-gen. DO NOT EDIT.

package basepb

import (
	buffer "github.com/mailru/easyjson/buffer"
	jwriter "github.com/mailru/easyjson/jwriter"
	objectpool "github.com/ravinggo/objectpool"
	zerolog "github.com/ravinggo/zerolog"
)

func (m *ErrorInfo) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("basepb.ErrorInfo error", err.Error())
	} else {
		e.RawJSON("basepb.ErrorInfo", d)
	}
}

func (m *ErrorMessage) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("basepb.ErrorMessage error", err.Error())
	} else {
		e.RawJSON("basepb.ErrorMessage", d)
	}
}

func (m *IntTrace) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("basepb.IntTrace error", err.Error())
	} else {
		e.RawJSON("basepb.IntTrace", d)
	}
}

func (m *Ping) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("basepb.Ping error", err.Error())
	} else {
		e.RawJSON("basepb.Ping", d)
	}
}

func (m *Pong) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("basepb.Pong error", err.Error())
	} else {
		e.RawJSON("basepb.Pong", d)
	}
}
