//go:build !ignore_autogenerated_zerolog
// +build !ignore_autogenerated_zerolog

// Code generated by zerolog-gen. DO NOT EDIT.

package basepb

import (
	buffer "github.com/mailru/easyjson/buffer"
	jwriter "github.com/mailru/easyjson/jwriter"
	objectpool "github.com/ravinggo/objectpool"
	zerolog "github.com/ravinggo/zerolog"
)

func (m *ErrorInfo) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("ErrorInfo error", err.Error())
	} else {
		e.RawJSON("ErrorInfo", d)
	}
}

func (m *ErrorMessage) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("ErrorMessage error", err.Error())
	} else {
		e.RawJSON("ErrorMessage", d)
	}
}

func (m *IntTrace) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("IntTrace error", err.Error())
	} else {
		e.RawJSON("IntTrace", d)
	}
}

func (m *StringTrace) MarshalZerologObject(e *zerolog.Event) {
	b := objectpool.GetBytes(2048)
	defer objectpool.PutBytes(b)
	w := jwriter.Writer{Buffer: buffer.Buffer{Buf: b}}
	m.MarshalEasyJSON(&w)
	d, err := w.BuildBytes()
	if err != nil {
		e.Str("StringTrace error", err.Error())
	} else {
		e.RawJSON("StringTrace", d)
	}
}
