//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package wholepkg

import (
	otherpkg "github.com/ravinggo/game/common/tools/deepcopy-gen/output_tests/otherpkg"
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ManualSlice) DeepCopyInto(ka *objectpool.KeepAlive, out *ManualSlice) {
	{
		in := &in
		*out = in.DeepCopy(ka)
		return
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualStruct) DeepCopyInto(ka *objectpool.KeepAlive, out *ManualStruct) {
	*out = in.DeepCopy(ka)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualStructAlias) DeepCopyInto(ka *objectpool.KeepAlive, out *ManualStructAlias) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualStructAlias.
func (in *ManualStructAlias) DeepCopy(ka *objectpool.KeepAlive) *ManualStructAlias {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[ManualStructAlias](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructB) DeepCopyInto(ka *objectpool.KeepAlive, out *StructB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructB.
func (in *StructB) DeepCopy(ka *objectpool.KeepAlive) *StructB {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructB](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedInt) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedInt) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedInt.
func (in *StructEmbedInt) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedInt {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedInt](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedManualStruct) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedManualStruct) {
	*out = *in
	out.ManualStruct = in.ManualStruct.DeepCopy(ka)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedManualStruct.
func (in *StructEmbedManualStruct) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedManualStruct {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedManualStruct](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedPointer) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedPointer) {
	*out = *in
	if in.int != nil {
		in, out := &in.int, &out.int
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedPointer.
func (in *StructEmbedPointer) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedPointer {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedPointer](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructPrimitivePointers) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedStructPrimitivePointers) {
	*out = *in
	in.StructPrimitivePointers.DeepCopyInto(ka, &out.StructPrimitivePointers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructPrimitivePointers.
func (in *StructEmbedStructPrimitivePointers) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedStructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedStructPrimitivePointers](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructPrimitives) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedStructPrimitives) {
	*out = *in
	out.StructPrimitives = in.StructPrimitives
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructPrimitives.
func (in *StructEmbedStructPrimitives) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedStructPrimitives {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedStructPrimitives](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmbedStructSlices) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmbedStructSlices) {
	*out = *in
	in.StructSlices.DeepCopyInto(ka, &out.StructSlices)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmbedStructSlices.
func (in *StructEmbedStructSlices) DeepCopy(ka *objectpool.KeepAlive) *StructEmbedStructSlices {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmbedStructSlices](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEmpty) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEmpty) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEmpty.
func (in *StructEmpty) DeepCopy(ka *objectpool.KeepAlive) *StructEmpty {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEmpty](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructEverything) DeepCopyInto(ka *objectpool.KeepAlive, out *StructEverything) {
	*out = *in
	out.StructField = in.StructField
	out.EmptyStructField = in.EmptyStructField
	out.ManualStructField = in.ManualStructField.DeepCopy(ka)
	out.ManualStructAliasField = in.ManualStructAliasField
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = objectpool.GetKA[bool](ka)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = objectpool.GetKA[string](ka)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = objectpool.GetKA[float64](ka)
		**out = **in
	}
	in.PrimitivePointersField.DeepCopyInto(ka, &out.PrimitivePointersField)
	if in.ManualStructPtrField != nil {
		in, out := &in.ManualStructPtrField, &out.ManualStructPtrField
		x := (*in).DeepCopy(ka)
		*out = &x
	}
	if in.ManualStructAliasPtrField != nil {
		in, out := &in.ManualStructAliasPtrField, &out.ManualStructAliasPtrField
		*out = objectpool.GetKA[ManualStructAlias](ka)
		**out = **in
	}
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = objectpool.GetKASliceSize[bool](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = objectpool.GetKASliceSize[byte](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = objectpool.GetKASliceSize[float64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	in.SlicesField.DeepCopyInto(ka, &out.SlicesField)
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = objectpool.GetKASliceSize[ManualStruct](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy(ka)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructEverything.
func (in *StructEverything) DeepCopy(ka *objectpool.KeepAlive) *StructEverything {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructEverything](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructExplicitObject) DeepCopyInto(ka *objectpool.KeepAlive, out *StructExplicitObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructExplicitObject.
func (in *StructExplicitObject) DeepCopy(ka *objectpool.KeepAlive) *StructExplicitObject {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructExplicitObject](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitObject) DeepCopyObject(ka *objectpool.KeepAlive) otherpkg.Object {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructExplicitSelectorExplicitObject) DeepCopyInto(ka *objectpool.KeepAlive, out *StructExplicitSelectorExplicitObject) {
	*out = *in
	out.StructTypeMeta = in.StructTypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructExplicitSelectorExplicitObject.
func (in *StructExplicitSelectorExplicitObject) DeepCopy(ka *objectpool.KeepAlive) *StructExplicitSelectorExplicitObject {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructExplicitSelectorExplicitObject](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructExplicitSelectorExplicitObject) DeepCopyObject(ka *objectpool.KeepAlive) otherpkg.Object {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopySelector is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *StructExplicitSelectorExplicitObject) DeepCopySelector(ka *objectpool.KeepAlive) Selector {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructInterfaces) DeepCopyInto(ka *objectpool.KeepAlive, out *StructInterfaces) {
	*out = *in
	if in.ObjectField != nil {
		out.ObjectField = in.ObjectField.DeepCopyObject(ka)
	}
	if in.NilObjectField != nil {
		out.NilObjectField = in.NilObjectField.DeepCopyObject(ka)
	}
	if in.SelectorField != nil {
		out.SelectorField = in.SelectorField.DeepCopySelector(ka)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructInterfaces.
func (in *StructInterfaces) DeepCopy(ka *objectpool.KeepAlive) *StructInterfaces {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructInterfaces](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructNonPointerExplicitObject) DeepCopyInto(ka *objectpool.KeepAlive, out *StructNonPointerExplicitObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructNonPointerExplicitObject.
func (in *StructNonPointerExplicitObject) DeepCopy(ka *objectpool.KeepAlive) *StructNonPointerExplicitObject {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructNonPointerExplicitObject](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in StructNonPointerExplicitObject) DeepCopyObject(ka *objectpool.KeepAlive) otherpkg.Object {
	return *in.DeepCopy(ka)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructObjectAndList) DeepCopyInto(ka *objectpool.KeepAlive, out *StructObjectAndList) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructObjectAndList.
func (in *StructObjectAndList) DeepCopy(ka *objectpool.KeepAlive) *StructObjectAndList {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructObjectAndList](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyList is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.List.
func (in *StructObjectAndList) DeepCopyList(ka *objectpool.KeepAlive) otherpkg.List {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndList) DeepCopyObject(ka *objectpool.KeepAlive) otherpkg.Object {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructObjectAndObject) DeepCopyInto(ka *objectpool.KeepAlive, out *StructObjectAndObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructObjectAndObject.
func (in *StructObjectAndObject) DeepCopy(ka *objectpool.KeepAlive) *StructObjectAndObject {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructObjectAndObject](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new otherpkg.Object.
func (in *StructObjectAndObject) DeepCopyObject(ka *objectpool.KeepAlive) otherpkg.Object {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivePointers) DeepCopyInto(ka *objectpool.KeepAlive, out *StructPrimitivePointers) {
	*out = *in
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = objectpool.GetKA[bool](ka)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = objectpool.GetKA[string](ka)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = objectpool.GetKA[float64](ka)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivePointers.
func (in *StructPrimitivePointers) DeepCopy(ka *objectpool.KeepAlive) *StructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructPrimitivePointers](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivePointersAlias) DeepCopyInto(ka *objectpool.KeepAlive, out *StructPrimitivePointersAlias) {
	*out = *in
	if in.BoolPtrField != nil {
		in, out := &in.BoolPtrField, &out.BoolPtrField
		*out = objectpool.GetKA[bool](ka)
		**out = **in
	}
	if in.IntPtrField != nil {
		in, out := &in.IntPtrField, &out.IntPtrField
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	if in.StringPtrField != nil {
		in, out := &in.StringPtrField, &out.StringPtrField
		*out = objectpool.GetKA[string](ka)
		**out = **in
	}
	if in.FloatPtrField != nil {
		in, out := &in.FloatPtrField, &out.FloatPtrField
		*out = objectpool.GetKA[float64](ka)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivePointersAlias.
func (in *StructPrimitivePointersAlias) DeepCopy(ka *objectpool.KeepAlive) *StructPrimitivePointersAlias {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructPrimitivePointersAlias](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitives) DeepCopyInto(ka *objectpool.KeepAlive, out *StructPrimitives) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitives.
func (in *StructPrimitives) DeepCopy(ka *objectpool.KeepAlive) *StructPrimitives {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructPrimitives](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructPrimitivesAlias) DeepCopyInto(ka *objectpool.KeepAlive, out *StructPrimitivesAlias) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructPrimitivesAlias.
func (in *StructPrimitivesAlias) DeepCopy(ka *objectpool.KeepAlive) *StructPrimitivesAlias {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructPrimitivesAlias](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructSlices) DeepCopyInto(ka *objectpool.KeepAlive, out *StructSlices) {
	*out = *in
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = objectpool.GetKASliceSize[bool](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = objectpool.GetKASliceSize[byte](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = objectpool.GetKASliceSize[float64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesField != nil {
		in, out := &in.SliceStructPrimitivesField, &out.SliceStructPrimitivesField
		*out = objectpool.GetKASliceSize[StructPrimitives](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in, out := &in.SliceStructPrimitivesAliasField, &out.SliceStructPrimitivesAliasField
		*out = objectpool.GetKASliceSize[StructPrimitivesAlias](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in, out := &in.SliceStructPrimitivePointersField, &out.SliceStructPrimitivePointersField
		*out = objectpool.GetKASliceSize[StructPrimitivePointers](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in, out := &in.SliceStructPrimitivePointersAliasField, &out.SliceStructPrimitivePointersAliasField
		*out = objectpool.GetKASliceSize[StructPrimitivePointersAlias](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	if in.SliceSliceIntField != nil {
		in, out := &in.SliceSliceIntField, &out.SliceSliceIntField
		*out = objectpool.GetKASliceSize[[]int](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
		}
	}
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = objectpool.GetKASliceSize[ManualStruct](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy(ka)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructSlices.
func (in *StructSlices) DeepCopy(ka *objectpool.KeepAlive) *StructSlices {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructSlices](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructSlicesAlias) DeepCopyInto(ka *objectpool.KeepAlive, out *StructSlicesAlias) {
	*out = *in
	if in.SliceBoolField != nil {
		in, out := &in.SliceBoolField, &out.SliceBoolField
		*out = objectpool.GetKASliceSize[bool](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceByteField != nil {
		in, out := &in.SliceByteField, &out.SliceByteField
		*out = objectpool.GetKASliceSize[byte](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceIntField != nil {
		in, out := &in.SliceIntField, &out.SliceIntField
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStringField != nil {
		in, out := &in.SliceStringField, &out.SliceStringField
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceFloatField != nil {
		in, out := &in.SliceFloatField, &out.SliceFloatField
		*out = objectpool.GetKASliceSize[float64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesField != nil {
		in, out := &in.SliceStructPrimitivesField, &out.SliceStructPrimitivesField
		*out = objectpool.GetKASliceSize[StructPrimitives](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivesAliasField != nil {
		in, out := &in.SliceStructPrimitivesAliasField, &out.SliceStructPrimitivesAliasField
		*out = objectpool.GetKASliceSize[StructPrimitivesAlias](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.SliceStructPrimitivePointersField != nil {
		in, out := &in.SliceStructPrimitivePointersField, &out.SliceStructPrimitivePointersField
		*out = objectpool.GetKASliceSize[StructPrimitivePointers](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	if in.SliceStructPrimitivePointersAliasField != nil {
		in, out := &in.SliceStructPrimitivePointersAliasField, &out.SliceStructPrimitivePointersAliasField
		*out = objectpool.GetKASliceSize[StructPrimitivePointersAlias](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	if in.SliceSliceIntField != nil {
		in, out := &in.SliceSliceIntField, &out.SliceSliceIntField
		*out = objectpool.GetKASliceSize[[]int](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
		}
	}
	if in.SliceManualStructField != nil {
		in, out := &in.SliceManualStructField, &out.SliceManualStructField
		*out = objectpool.GetKASliceSize[ManualStruct](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	out.ManualSliceField = in.ManualSliceField.DeepCopy(ka)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructSlicesAlias.
func (in *StructSlicesAlias) DeepCopy(ka *objectpool.KeepAlive) *StructSlicesAlias {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructSlicesAlias](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructPrimitivePointers) DeepCopyInto(ka *objectpool.KeepAlive, out *StructStructPrimitivePointers) {
	*out = *in
	in.StructField.DeepCopyInto(ka, &out.StructField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructPrimitivePointers.
func (in *StructStructPrimitivePointers) DeepCopy(ka *objectpool.KeepAlive) *StructStructPrimitivePointers {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructStructPrimitivePointers](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructPrimitives) DeepCopyInto(ka *objectpool.KeepAlive, out *StructStructPrimitives) {
	*out = *in
	out.StructField = in.StructField
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructPrimitives.
func (in *StructStructPrimitives) DeepCopy(ka *objectpool.KeepAlive) *StructStructPrimitives {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructStructPrimitives](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructStructSlices) DeepCopyInto(ka *objectpool.KeepAlive, out *StructStructSlices) {
	*out = *in
	in.StructField.DeepCopyInto(ka, &out.StructField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructStructSlices.
func (in *StructStructSlices) DeepCopy(ka *objectpool.KeepAlive) *StructStructSlices {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[StructStructSlices](ka)
	in.DeepCopyInto(ka, out)
	return out
}
