//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package maps

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Byte != nil {
		in, out := &in.Byte, &out.Byte
		*out = objectpool.GetKAMap[string, byte](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Int16 != nil {
		in, out := &in.Int16, &out.Int16
		*out = objectpool.GetKAMap[string, int16](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Int32 != nil {
		in, out := &in.Int32, &out.Int32
		*out = objectpool.GetKAMap[string, int32](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Int64 != nil {
		in, out := &in.Int64, &out.Int64
		*out = objectpool.GetKAMap[string, int64](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Uint8 != nil {
		in, out := &in.Uint8, &out.Uint8
		*out = objectpool.GetKAMap[string, byte](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Uint16 != nil {
		in, out := &in.Uint16, &out.Uint16
		*out = objectpool.GetKAMap[string, uint16](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Uint32 != nil {
		in, out := &in.Uint32, &out.Uint32
		*out = objectpool.GetKAMap[string, uint32](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Uint64 != nil {
		in, out := &in.Uint64, &out.Uint64
		*out = objectpool.GetKAMap[string, uint64](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Float32 != nil {
		in, out := &in.Float32, &out.Float32
		*out = objectpool.GetKAMap[string, float32](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Float64 != nil {
		in, out := &in.Float64, &out.Float64
		*out = objectpool.GetKAMap[string, float64](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = objectpool.GetKAMap[string, string](ka)
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StringPtr != nil {
		in, out := &in.StringPtr, &out.StringPtr
		*out = objectpool.GetKAMap[string, *string](ka)
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKA[string](ka)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.StringPtrPtr != nil {
		in, out := &in.StringPtrPtr, &out.StringPtrPtr
		*out = objectpool.GetKAMap[string, **string](ka)
		for key, val := range *in {
			var outVal **string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKA[*string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKA[string](ka)
					**out = **in
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = objectpool.GetKAMap[string, map[string]string](ka)
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKAMap[string, string](ka)
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.MapPtr != nil {
		in, out := &in.MapPtr, &out.MapPtr
		*out = objectpool.GetKAMap[string, *map[string]string](ka)
		for key, val := range *in {
			var outVal *map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKA[map[string]string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKAMap[string, string](ka)
					for key, val := range *in {
						(*out)[key] = val
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Slice != nil {
		in, out := &in.Slice, &out.Slice
		*out = objectpool.GetKAMap[string, []string](ka)
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.SlicePtr != nil {
		in, out := &in.SlicePtr, &out.SlicePtr
		*out = objectpool.GetKAMap[string, *[]string](ka)
		for key, val := range *in {
			var outVal *[]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKA[[]string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
					copy(*out, *in)
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Struct != nil {
		in, out := &in.Struct, &out.Struct
		*out = objectpool.GetKAMap[string, Ttest](ka)
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy(ka)
		}
	}
	if in.StructPtr != nil {
		in, out := &in.StructPtr, &out.StructPtr
		*out = objectpool.GetKAMap[string, *Ttest](ka)
		for key, val := range *in {
			var outVal *Ttest
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKA[Ttest](ka)
				(*in).DeepCopyInto(ka, *out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
