//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package slices

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Byte != nil {
		in, out := &in.Byte, &out.Byte
		*out = objectpool.GetKASliceSize[byte](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Int16 != nil {
		in, out := &in.Int16, &out.Int16
		*out = objectpool.GetKASliceSize[int16](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Int32 != nil {
		in, out := &in.Int32, &out.Int32
		*out = objectpool.GetKASliceSize[int32](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Int64 != nil {
		in, out := &in.Int64, &out.Int64
		*out = objectpool.GetKASliceSize[int64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Uint8 != nil {
		in, out := &in.Uint8, &out.Uint8
		*out = objectpool.GetKASliceSize[byte](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Uint16 != nil {
		in, out := &in.Uint16, &out.Uint16
		*out = objectpool.GetKASliceSize[uint16](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Uint32 != nil {
		in, out := &in.Uint32, &out.Uint32
		*out = objectpool.GetKASliceSize[uint32](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Uint64 != nil {
		in, out := &in.Uint64, &out.Uint64
		*out = objectpool.GetKASliceSize[uint64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Float32 != nil {
		in, out := &in.Float32, &out.Float32
		*out = objectpool.GetKASliceSize[float32](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Float64 != nil {
		in, out := &in.Float64, &out.Float64
		*out = objectpool.GetKASliceSize[float64](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.StringPtr != nil {
		in, out := &in.StringPtr, &out.StringPtr
		*out = objectpool.GetKASliceSize[*string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKA[string](ka)
				**out = **in
			}
		}
	}
	if in.StringPtrPtr != nil {
		in, out := &in.StringPtrPtr, &out.StringPtrPtr
		*out = objectpool.GetKASliceSize[**string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKA[*string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKA[string](ka)
					**out = **in
				}
			}
		}
	}
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = objectpool.GetKASliceSize[map[string]string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKAMap[string, string](ka)
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.MapPtr != nil {
		in, out := &in.MapPtr, &out.MapPtr
		*out = objectpool.GetKASliceSize[*map[string]string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKA[map[string]string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKAMap[string, string](ka)
					for key, val := range *in {
						(*out)[key] = val
					}
				}
			}
		}
	}
	if in.Slice != nil {
		in, out := &in.Slice, &out.Slice
		*out = objectpool.GetKASliceSize[[]string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
		}
	}
	if in.SlicePtr != nil {
		in, out := &in.SlicePtr, &out.SlicePtr
		*out = objectpool.GetKASliceSize[*[]string](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKA[[]string](ka)
				if **in != nil {
					in, out := *in, *out
					*out = objectpool.GetKASliceSize[string](ka, len(*in), len(*in)).Data
					copy(*out, *in)
				}
			}
		}
	}
	if in.Struct != nil {
		in, out := &in.Struct, &out.Struct
		*out = objectpool.GetKASliceSize[Ttest](ka, len(*in), len(*in)).Data
		for i := range *in {
			(*in)[i].DeepCopyInto(ka, &(*out)[i])
		}
	}
	if in.StructPtr != nil {
		in, out := &in.StructPtr, &out.StructPtr
		*out = objectpool.GetKASliceSize[*Ttest](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKA[Ttest](ka)
				(*in).DeepCopyInto(ka, *out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
