//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package aliases

import (
	objectpool "github.com/ravinggo/objectpool"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasInterfaceMap) DeepCopyInto(ka *objectpool.KeepAlive, out *AliasInterfaceMap) {
	{
		in := &in
		*out = AliasInterfaceMap(objectpool.GetKAMap[string, AliasInterface](ka))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyAliasInterface(ka)
			}
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasInterfaceMap.
func (in AliasInterfaceMap) DeepCopy(ka *objectpool.KeepAlive) AliasInterfaceMap {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[AliasInterfaceMap](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasInterfaceSlice) DeepCopyInto(ka *objectpool.KeepAlive, out *AliasInterfaceSlice) {
	{
		in := &in
		*out = objectpool.GetKASliceSize[AliasInterface](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyAliasInterface(ka)
			}
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasInterfaceSlice.
func (in AliasInterfaceSlice) DeepCopy(ka *objectpool.KeepAlive) AliasInterfaceSlice {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[AliasInterfaceSlice](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasMap) DeepCopyInto(ka *objectpool.KeepAlive, out *AliasMap) {
	{
		in := &in
		*out = AliasMap(objectpool.GetKAMap[string, int](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasMap.
func (in AliasMap) DeepCopy(ka *objectpool.KeepAlive) AliasMap {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[AliasMap](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasSlice) DeepCopyInto(ka *objectpool.KeepAlive, out *AliasSlice) {
	{
		in := &in
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasSlice.
func (in AliasSlice) DeepCopy(ka *objectpool.KeepAlive) AliasSlice {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[AliasSlice](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliasStruct) DeepCopyInto(ka *objectpool.KeepAlive, out *AliasStruct) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasStruct.
func (in *AliasStruct) DeepCopy(ka *objectpool.KeepAlive) *AliasStruct {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[AliasStruct](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Foo) DeepCopyInto(ka *objectpool.KeepAlive, out *Foo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Foo.
func (in *Foo) DeepCopy(ka *objectpool.KeepAlive) *Foo {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Foo](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyAliasAliasInterface is an autogenerated deepcopy function, copying the receiver, creating a new AliasAliasInterface.
func (in *Foo) DeepCopyAliasAliasInterface(ka *objectpool.KeepAlive) AliasAliasInterface {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyAliasInterface is an autogenerated deepcopy function, copying the receiver, creating a new AliasInterface.
func (in *Foo) DeepCopyAliasInterface(ka *objectpool.KeepAlive) AliasInterface {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Foo) DeepCopyInterface(ka *objectpool.KeepAlive) Interface {
	if c := in.DeepCopy(ka); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FooAlias) DeepCopyInto(ka *objectpool.KeepAlive, out *FooAlias) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FooAlias.
func (in *FooAlias) DeepCopy(ka *objectpool.KeepAlive) *FooAlias {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[FooAlias](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FooMap) DeepCopyInto(ka *objectpool.KeepAlive, out *FooMap) {
	{
		in := &in
		*out = FooMap(objectpool.GetKAMap[string, Foo](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FooMap.
func (in FooMap) DeepCopy(ka *objectpool.KeepAlive) FooMap {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[FooMap](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FooSlice) DeepCopyInto(ka *objectpool.KeepAlive, out *FooSlice) {
	{
		in := &in
		*out = objectpool.GetKASliceSize[Foo](ka, len(*in), len(*in)).Data
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FooSlice.
func (in FooSlice) DeepCopy(ka *objectpool.KeepAlive) FooSlice {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[FooSlice](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Map) DeepCopyInto(ka *objectpool.KeepAlive, out *Map) {
	{
		in := &in
		*out = Map(objectpool.GetKAMap[string, int](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Map.
func (in Map) DeepCopy(ka *objectpool.KeepAlive) Map {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Map](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Slice) DeepCopyInto(ka *objectpool.KeepAlive, out *Slice) {
	{
		in := &in
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Slice.
func (in Slice) DeepCopy(ka *objectpool.KeepAlive) Slice {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Slice](ka)
	in.DeepCopyInto(ka, out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Struct) DeepCopyInto(ka *objectpool.KeepAlive, out *Struct) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Struct.
func (in *Struct) DeepCopy(ka *objectpool.KeepAlive) *Struct {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Struct](ka)
	in.DeepCopyInto(ka, out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ttest) DeepCopyInto(ka *objectpool.KeepAlive, out *Ttest) {
	*out = *in
	if in.Slice != nil {
		in, out := &in.Slice, &out.Slice
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.Pointer != nil {
		in, out := &in.Pointer, &out.Pointer
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	if in.PointerAlias != nil {
		in, out := &in.PointerAlias, &out.PointerAlias
		*out = objectpool.GetKA[Builtin](ka)
		**out = **in
	}
	out.Struct = in.Struct
	if in.Map != nil {
		in, out := &in.Map, &out.Map
		*out = Map(objectpool.GetKAMap[string, int](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SliceSlice != nil {
		in, out := &in.SliceSlice, &out.SliceSlice
		*out = objectpool.GetKASliceSize[Slice](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
		}
	}
	if in.MapSlice != nil {
		in, out := &in.MapSlice, &out.MapSlice
		*out = objectpool.GetKAMap[string, Slice](ka)
		for key, val := range *in {
			var outVal []int
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	out.FooAlias = in.FooAlias
	if in.FooSlice != nil {
		in, out := &in.FooSlice, &out.FooSlice
		*out = objectpool.GetKASliceSize[Foo](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.FooPointer != nil {
		in, out := &in.FooPointer, &out.FooPointer
		*out = objectpool.GetKA[Foo](ka)
		**out = **in
	}
	if in.FooMap != nil {
		in, out := &in.FooMap, &out.FooMap
		*out = FooMap(objectpool.GetKAMap[string, Foo](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AliasSlice != nil {
		in, out := &in.AliasSlice, &out.AliasSlice
		*out = objectpool.GetKASliceSize[int](ka, len(*in), len(*in)).Data
		copy(*out, *in)
	}
	if in.AliasPointer != nil {
		in, out := &in.AliasPointer, &out.AliasPointer
		*out = objectpool.GetKA[int](ka)
		**out = **in
	}
	out.AliasStruct = in.AliasStruct
	if in.AliasMap != nil {
		in, out := &in.AliasMap, &out.AliasMap
		*out = AliasMap(objectpool.GetKAMap[string, int](ka))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AliasInterface != nil {
		out.AliasInterface = in.AliasInterface.DeepCopyAliasInterface(ka)
	}
	if in.AliasAliasInterface != nil {
		out.AliasAliasInterface = in.AliasAliasInterface.DeepCopyAliasAliasInterface(ka)
	}
	if in.AliasInterfaceMap != nil {
		in, out := &in.AliasInterfaceMap, &out.AliasInterfaceMap
		*out = AliasInterfaceMap(objectpool.GetKAMap[string, AliasInterface](ka))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyAliasInterface(ka)
			}
		}
	}
	if in.AliasInterfaceSlice != nil {
		in, out := &in.AliasInterfaceSlice, &out.AliasInterfaceSlice
		*out = objectpool.GetKASliceSize[AliasInterface](ka, len(*in), len(*in)).Data
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyAliasInterface(ka)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ttest.
func (in *Ttest) DeepCopy(ka *objectpool.KeepAlive) *Ttest {
	if in == nil {
		return nil
	}
	out := objectpool.GetKA[Ttest](ka)
	in.DeepCopyInto(ka, out)
	return out
}
